### ISSUE TITLE
UTAnnouncer addon won't play certain SFX

### ISSUE THREAD

**Issue by bensegal2034** [bensegal2034/TTT_Custom_Server_V2#14]
The sound effects for double and triple killstreaks refuse to play for some reason. They download properly on the client, which is confirmable by checking the `/garrysmod/download/` folder clientside. However, the game believes the files don't exist and an error appears in console when trying to play them. All other audio files in the addon work fine.

**Comment by CosmicFlare3** [comment]
Fixed on newest commit.
This was a result of 1 or both of the following problems,
The mp3 version of the sound effects never had respective resource.AddFile() lines
The sample rate was incorrect on the wav/mp3 files, unsure if it was an incompatible sample rate, but fixed it regardless
